//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public short IdCom { get; set; }
        public string nameCom { get; set; }
        public string email { get; set; }
        public string messageC { get; set; }
        public Nullable<short> posteId { get; set; }
    
        public virtual poste poste { get; set; }
    }
}
