//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class poste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public poste()
        {
            this.comment = new HashSet<comment>();
        }
    
        public short idp { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> datePublication { get; set; }
        public Nullable<short> categoryId { get; set; }
        public Nullable<short> userId { get; set; }
        public Nullable<int> viewCount { get; set; }
    
        public virtual bloguser bloguser { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
    }
}
